agent:
    container_name: ci.dmp-api-autotest-122-1
    hostname: ci.dmp-api-autotest-122-1
    image: docker-registry:5000/actiontech/dmp-api-autotest-agent:latest
    privileged: true
    restart: always
    volumes:
      - "/opt/docker:/var/lib/docker"
    ports:
      - "8722:8722"
      - "8708:8708"
      - "8709:8709"
      - "8713:8713"
      - "8715:8715"
      - "8799:8799"
    extra_hosts:
      - "docker-registry:10.186.18.20"
      - "gocd-server:10.186.18.19"
